version: 2

sources:
  - name: ipma_raw
    schema: raw          # <-- ajuste
    tables:
      - name: ipma_observations_raw    # <-- ajuste

models:
  - name: stg_ipma_observations
    columns:
      - name: dt
        tests: [not_null]
      - name: station_id
        tests: [not_null]
