version: 2

sources:
  - name: ipma
    schema: raw
    tables:
      - name: ipma_observations_raw
        description: "Observações IPMA cruas; payload é JSON com {timestamp -> {station_id -> medidas}}"

models:
  - name: stg_ipma_observations
    description: "Observações normalizadas (1 linha por station_id + timestamp)"
    columns:
      - name: ingested_at
      - name: dt
      - name: hour
      - name: observation_ts
      - name: station_id
